# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

        Symfony\Component\Security\Core\User\User: plaintext

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: 'ROLE_ADMIN' }

        database_users:
            entity:
                class: AppBundle:User
                property: login

        jwt_key_user_provider:
            id: AppBundle\Security\JwtKeyUserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            anonymous: ~
            simple_preauth:
                authenticator: AppBundle\Security\JwtKeyAuthenticator
            stateless: true
            provider: jwt_key_user_provider

        admin:
            pattern: ^/admin
            http_basic:
                provider: in_memory
                realm: "Super Admin section!"
            stateless:  true
            logout: { path: /admin/logout, target: / }

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }


