services:
    _defaults:
        autowire: true
        autoconfigure: true

    kernel.listener.app_request_listener:
        class: AppBundle\EventListener\AppRequestListener
        arguments: ['@service_container', '@doctrine_logger']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 7 }

    kernel.listener.app_response_listener:
        class: AppBundle\EventListener\AppResponseListener
        arguments: ['@Doctrine\DBAL\Logging\DebugStack']
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    kernel.listener.app_exception_listener:
        class: AppBundle\EventListener\AppExceptionListener
        arguments: ['@serializer', '@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    AppBundle\EventListener\User\UserRemoveListener:
        tags:
          - { name: kernel.event_listener, event: user.removed, method: onUserRemoved }

    AppBundle\EventListener\User\UserRegisterListener:
        tags:
          - { name: kernel.event_listener, event: user.registered, method: onUserRegistered }