AppBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        firstName:
            type: string
            length: 80
            nullable: true

        lastName:
            type: string
            length: 80,
            nullable: true

        login:
            type: string
            length: 80

        password:
            type: string
            length: 60

        email:
            type: string
            length: 80
            unique: true

        role:
            type: string
            length: 40
