AppBundle\Entity\User:
    attributes:
        id:
            groups: ['list']

        login:
            groups: ['list']

        firstName:
            groups: ['list']

        lastName:
            groups: ['list']

        fullName:
            groups: ['list']

        email:
            groups: ['list']

        role:
            groups: ['role_admin']
