AppBundle\Entity\User:
    attributes:
        id:
            groups: ['list']
        firstName:
            groups: ['list']
        lastName:
            groups: ['list']
        fullName:
            groups: ['list']