AppBundle\Entity\User:
    properties:
        login:
            - NotBlank: { groups: [registration] }

        password:
            - NotBlank: { groups: [registration] }

        lastName:
            - NotBlank: { groups: [registration]}