AppBundle\Entity\User:
    properties:
        login:
            - NotBlank: { groups: [registration, login] }

        password:
            - NotBlank: { groups: [registration, login] }
            - Length: { min: 8, groups: [registration] }

        lastName:
            - NotBlank: { groups: [registration]}

        firstName:
            - Type: { type: string, groups: [update]}
            - Length: { min: 2, groups: [update]}
            - NotNull: { message: 'This value can not be empty.', groups: [update] }
