AppBundle\Entity\User:
    properties:
        login:
            - NotBlank: { groups: [registration, login] }

        password:
            - NotBlank: { groups: [registration, login] }
            - Length: { min: 8, groups: [registration] }

        lastName:
            - NotBlank: { groups: [registration]}