AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        login:
            - NotBlank: { groups: [registration, login] }

        password:
            - NotBlank: { groups: [registration, login] }
            - Length: { min: 8, groups: [registration] }

        lastName:
            - Type: { type: string, groups: [update]}
            - Length: { min: 2, groups: [update] }

        firstName:
            - Type: { type: string, groups: [update]}
            - Length: { min: 2, groups: [update]}
            - NotNull: { message: 'This value can not be empty.', groups: [update] }

        email:
            - NotBlank: { groups: [registration] }
            - Email: { groups: [registration] }
